name: Install Release
description: GitHub Action that downloads a release and provision for later job usage
author: KeisukeYamashita and open-turo
inputs:
  arch:
    required: false
    description: The asset arch target
    default: amd64
  archive:
    required: false
    description: The extension. "tar.gz", "darwin", "zip" is supported
    default: tar.gz
  installPath:
    required: false
    description: Path to install the extracted asset
    default: ''
  repository:
    required: false
    description: The GitHub repository to get the release
    default: ${{ github.repository }}
  platform:
    required: false
    description: The asset target platform
    default: linux
  tag:
    required: false
    description: The release tag
    default: latest
  token:
    required: false
    description: Credential to access to the repo to post the comment
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
branding:
  icon: archive
  color: orange
